feat: automates package installation
mem0ai/mem0 pull request #1780
Opened 2024-08-30 05:01 UTC by Jai0401

## Description

Implement a mechanism to automatically prompt users to install missing packages. If they agree, the required package will be installed.

- progresses #1768 

Updated files:
`mem0/configs/vector_stores/chroma.py`
`mem0/llms/aws_bedrock.py`

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (does not change functionality, e.g. code style improvements, linting)
- [ ] Documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Please delete options that are not relevant.

- [ ] Unit Test
- [ ] Test Script (please provide)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] Made sure Checks passed

2024-08-30 17:27 UTC, Dev-Khant requested changes
Hey @Jai0401 Please avoid creating the functions here for checking if the package has been installed or not. You can directly use the code snippet that you provided in issue description.

2024-08-30 18:12 UTC, Jai0401 commented
@Dev-Khant I've made the changes requested in the previous review. Could you please take a look and let me know if everything is in order or if any further adjustments are needed?

2024-08-31 20:25 UTC, Dev-Khant commented on mem0/configs/vector_stores/chroma.py
>      try:
Can you please move this import statement out from the class.

2024-08-31 20:26 UTC, Dev-Khant reviewed
Also can you please make changes from groq, litellm, together and ollama llms.

2024-08-31 22:37 UTC, Jai0401 commented
@Dev-Khant I've made the requested changes. Please review them and let me know if any further adjustments are needed.

2024-09-02 14:30 UTC, Dev-Khant commented on mem0/configs/vector_stores/chroma.py
> -    try:
Hey @Jai0401 Really sorry my bad, can you please keep the import statement inside the class.

2024-09-02 14:32 UTC, Dev-Khant reviewed
Rest looks good, left a small comment for `chromadb`.

2024-09-02 14:47 UTC, Jai0401 commented
@Dev-Khant  I've made the requested changes.

2024-09-02 14:53 UTC, Dev-Khant approved these changes

2024-09-02 14:53 UTC, merged